### ISSUE TITLE
 Responsive menu

### ISSUE THREAD

**Issue by spectralshard** [betes-curieuses-design/AllianceEducation#1]
Pour le menu:

Tablette: Reduire la taille de police
Mobile: Mettre les lien à 100% de l'espace, centré et ajuster pour qu'on soit capable de client sur le lien contact lorsqu'on est au début de la page (petit bug, où il non clickable.

**Comment by spectralshard** [comment]
Fix, the mobile 100% space. Still some issue for the nav:

Desktop: Submenu > remove rounded corner.
Tablette/Desktop: reduce the padding (could found where it control); also made it fix height so when we hover the menu it not moving.
Mobile: Try to fix the height when we open the hamburger icon.

I have fix the link issue on mobile (forgot the link there :D )

**Comment by lorajc** [comment]
Desktop: Submenu > remove rounded corner. Fixed
Tablette/Desktop: reduce the padding (could found where it control); also made it fix height so when we hover the menu it not moving.. Fixed

**Comment by lorajc** [comment]
Mobile: Try to fix the height when we open the hamburger icon. Fixed

**Comment by spectralshard** [comment]
Oh god! your a hero my friend! ;-D
