### ISSUE TITLE
Services pages: right panel issue

### ISSUE THREAD

**Issue by spectralshard** [betes-curieuses-design/AllianceEducation#10]
Center typo and hr element. And for mobile have a row for each? Thank a million! :-)

![capture d ecran 2015-11-25 a 20 57 46](https://cloud.githubusercontent.com/assets/11337449/11413735/aab0acfe-93ba-11e5-9bf7-c679362ae8ae.png)
![capture d ecran 2015-11-25 a 20 57 53](https://cloud.githubusercontent.com/assets/11337449/11413736/aabdad00-93ba-11e5-843c-3d0840ecb944.png)

**Comment by lorajc** [comment]
Fixed!
