### ISSUE TITLE
Backend - Education(proBlog) Comment

### ISSUE THREAD

**Issue by spectralshard** [betes-curieuses-design/AllianceEducation#12]
C'est quoi la différence entre la version avec et sans S pour éviter de mélanger la cliente ahaha?
![capture d ecran 2015-11-25 a 21 29 19](https://cloud.githubusercontent.com/assets/11337449/11413827/a6a477ac-93bb-11e5-8430-45fb23f484cb.png)

**Comment by lorajc** [comment]
S plural (many)

**Comment by spectralshard** [comment]
So she add the new items always in the plural form??
