### ISSUE TITLE
Date de parution - Capsule

### ISSUE THREAD

**Issue by spectralshard** [betes-curieuses-design/AllianceEducation#13]
Les dates de parution des capsules ne sont pas les même que celui dans le backend, ni dans la page vu d'une capsule.
![capture d ecran 2015-11-26 a 21 59 13](https://cloud.githubusercontent.com/assets/11337449/11433301/4099f24c-9489-11e5-8e84-200906ccdb7a.png)

![capture d ecran 2015-11-26 a 21 59 01](https://cloud.githubusercontent.com/assets/11337449/11433302/4381dfb0-9489-11e5-8712-28eae7c6fd38.png)

**Comment by lorajc** [comment]
Fixed!

**Comment by spectralshard** [comment]
Nice! :-)
