### ISSUE TITLE
Module de création Éducation (questionnement)

### ISSUE THREAD

**Issue by spectralshard** [betes-curieuses-design/AllianceEducation#14]
Lors d'une création de capsule, si les champs du bas ne sont pas rempli, est-ce normal de tombé là dessus??
![capture d ecran 2015-11-26 a 20 49 25](https://cloud.githubusercontent.com/assets/11337449/11433319/81fdfe68-9489-11e5-852f-6c6ff564e9a0.png)

**Comment by lorajc** [comment]
Fixed!, je t'envoie la nouvelle bd, j'ai fait le changement en prod sans écraser la bd

**Comment by spectralshard** [comment]
Merci, la client était vérifier de voir ça XD
