### ISSUE TITLE
Retour à la liste (Conférence et Capsule)

### ISSUE THREAD

**Issue by spectralshard** [betes-curieuses-design/AllianceEducation#15]
On ne retourne pas vers la catégorie approprier (toujours vers Formation). Ce bouton n'est pas présent dans l'article d'un blogue, si tu peux le rajouter :)
![capture d ecran 2015-11-26 a 22 04 31](https://cloud.githubusercontent.com/assets/11337449/11433332/b0ce1c00-9489-11e5-8826-1c1cfb20eb89.png)

**Comment by lorajc** [comment]
Done!

**Comment by spectralshard** [comment]
Work! Thank!
