### ISSUE TITLE
REQUEST - Module d'inscription backend

### ISSUE THREAD

**Issue by spectralshard** [betes-curieuses-design/AllianceEducation#16]
Peut-tu ajouter Titre de formation/conference auquel il est relier, je crois que ça va donner un coup de mains pour la gestion et une fonction supprimé pour les entré de donner (si quelqu'un cancel^^)? : ) 
![capture d ecran 2015-11-27 a 19 57 26](https://cloud.githubusercontent.com/assets/11337449/11449392/4127e4c2-9541-11e5-8d2a-e2844fc7ab07.png)

**Comment by lorajc** [comment]
Done!

**Comment by spectralshard** [comment]
Perfect!
