### ISSUE TITLE
Pagination dans le blog

### ISSUE THREAD

**Issue by spectralshard** [betes-curieuses-design/AllianceEducation#17]
Peu ton placé les paginations (flow de lecture) et N'avoir que les flèche? (Je pensais mettre le texte en français, mais je crois que ça va être trop long :/ Si tu veux assayer c'est <- Précédent et Suivant ->. Qu'en pense tu?
![capture d écran 2015-11-27 a 20 26 14](https://cloud.githubusercontent.com/assets/11337449/11449483/871ff8e4-9545-11e5-8ee3-fefe2bf4d140.png)

En fait prend le style de pro blog :-)
![capture d ecran 2015-11-27 a 20 37 35](https://cloud.githubusercontent.com/assets/11337449/11449517/c7a85090-9546-11e5-987c-d05d1b1ddd40.png)

**Comment by spectralshard** [comment]
Bug on local host XD

**Comment by lorajc** [comment]
Done!

**Comment by spectralshard** [comment]
parfait!
