### ISSUE TITLE
Page Capsules (Archives des capsules)

### ISSUE THREAD

**Issue by spectralshard** [betes-curieuses-design/AllianceEducation#18]
Mettre 6 par page (comme les deux autres :-) ) et mettre un peu plus d'espace vers le bas entre les deux row de capsules (ça l'aire pogné, comme dirais mon papa!)

![capture d ecran 2015-11-27 a 20 34 45](https://cloud.githubusercontent.com/assets/11337449/11449543/136b3aa0-9548-11e5-8779-df7ed57f8abc.png)

**Comment by lorajc** [comment]
Done!

**Comment by spectralshard** [comment]
good!
