### ISSUE TITLE
Page Formations et Conférences (Toute les formations/ Conférences)

### ISSUE THREAD

**Issue by spectralshard** [betes-curieuses-design/AllianceEducation#19]
De l'espace aussi ici entre les rows! : )
![capture d ecran 2015-11-27 a 20 48 20](https://cloud.githubusercontent.com/assets/11337449/11449547/40d9c90c-9548-11e5-8d28-8f762b6653eb.png)

Oh et oublie pas de m'activé les feature images :-) merci bcp!!!

**Comment by lorajc** [comment]
Fixed!

**Comment by spectralshard** [comment]
Perfect!
