### ISSUE TITLE
Pro Blog (Les trois)

### ISSUE THREAD

**Issue by spectralshard** [betes-curieuses-design/AllianceEducation#20]
Description en H3 (mettre un peu de contrast : ) ) merci!

![e0a17988-9540-11e5-8cd5-a04b00abafeb](https://cloud.githubusercontent.com/assets/11337449/11449586/5afc0984-9549-11e5-88c2-87fb13fcb787.png)

**Comment by lorajc** [comment]
Done!

**Comment by spectralshard** [comment]
Let roll!
