### ISSUE TITLE
Blogue - Mobile view visual bug

### ISSUE THREAD

**Issue by spectralshard** [betes-curieuses-design/AllianceEducation#21]
Peut-on arranger ça (mettre a 100% en mobile) ?
![capture d ecran 2015-11-27 a 21 00 19](https://cloud.githubusercontent.com/assets/11337449/11449599/f4045578-9549-11e5-8439-b70d0054bb2e.png)

**Comment by lorajc** [comment]
Fixed!

**Comment by spectralshard** [comment]
:+1:
