### ISSUE TITLE
Contact page - Mobile space issue

### ISSUE THREAD

**Issue by spectralshard** [betes-curieuses-design/AllianceEducation#22]
Le courriel qui est trop long?? Peut-être mettre plus petit en mobile?
![img_0352](https://cloud.githubusercontent.com/assets/11337449/11449641/457b7048-954b-11e5-8efe-d0413e4eb402.PNG)

**Comment by lorajc** [comment]
Fixed!

**Comment by spectralshard** [comment]
:+1:
