### ISSUE TITLE
Menu issue on iPad

### ISSUE THREAD

**Issue by spectralshard** [betes-curieuses-design/AllianceEducation#23]
Not sure if it fixable, the arrows for sub menu do not appear, but does on iPhone.. it maybe my old crazy iPad through :P 

Can we move the slide dots a bit to the bottom ? :)

That gonna be all until you fix and finish everything. Give me a call one it fix, so I can give a full review again... and finally get $$$ of this ahaha!
![img_0407](https://cloud.githubusercontent.com/assets/11337449/11449692/52f262ac-954d-11e5-9adf-53fb9230561d.PNG)

**Comment by lorajc** [comment]
I tried but sorry I don't know :(

**Comment by spectralshard** [comment]
Okay! Let keep it like this, not that impact anything!
