### ISSUE TITLE
Dernière formation - Image Dupliqué

### ISSUE THREAD

**Issue by spectralshard** [betes-curieuses-design/AllianceEducation#24]
Sur la page d'accueil (seulement pour cela.. conférence est okay!), il duplique l'image 2 fois! Si tu peux arranger ça et on va être okay!
![capture d ecran 2015-11-28 a 16 58 10](https://cloud.githubusercontent.com/assets/11337449/11454193/4fbbb8a4-95f2-11e5-859c-15494af4676a.png)

**Comment by lorajc** [comment]
Fixed
