### ISSUE TITLE
Module d'inscription (formation et conférence)

### ISSUE THREAD

**Issue by spectralshard** [betes-curieuses-design/AllianceEducation#25]
Est-ce possible de mettre à jours l'affichage sur la page de catégorie et intérieur. ( # jusqu'à 0 (a 0 on enlève le bouton)

![capture d ecran 2015-11-28 a 16 49 47](https://cloud.githubusercontent.com/assets/11337449/11454214/db8a36b2-95f2-11e5-9e96-2c5ac31b9e4d.png)

J'ai réussi a mettre un a 5 et inscrire 6 personne sans que le système disse que c'est plein. Il faudrait réglé le tout :)

![capture d ecran 2015-11-28 a 16 50 07](https://cloud.githubusercontent.com/assets/11337449/11454210/d11cbff6-95f2-11e5-871e-bae951d49f92.png)

**Comment by lorajc** [comment]
Fixed!
