### ISSUE TITLE
Partage d'article du blog

### ISSUE THREAD

**Issue by spectralshard** [betes-curieuses-design/AllianceEducation#27]
Lorsqu'on partage un article sur le blog, aucune image n'est prix en compte et la cliente aimerais avoir le titre de son article (à la place de "Article" si possible. Peux-tu mettre le code pour collecter le feature image? Merci :-)

![capture d ecran 2016-01-02 a 16 54 30](https://cloud.githubusercontent.com/assets/11337449/12076267/d77c1e38-b171-11e5-9e5a-a6f09f2744f6.png)

(Pense tu qu'on devrait ajouter un module de partage dans cette section, la client est prête a payer si tu le rajoute dans la prochain version, si tu a du temps bien sûr!) :-)

-Alex

**Comment by spectralshard** [comment]
J'ai testé.. et ça doit être la fonction blizzard qui empêche le partage de l'image d'article dans le blog.. le reste ça fonctionne. Je sais que j'ai rajouter dans le code, le bon title et le code google webmaster pour le référencement... mais le reste j'attend des nouvelles de la cliente...

![capture d ecran 2016-01-06 a 19 55 23](https://cloud.githubusercontent.com/assets/11337449/12159445/464f5f5a-b4b0-11e5-9649-1f261e374417.png)

**Comment by spectralshard** [comment]
Pour le titre non fonctionnel, c'est corriger avec la dernière version de GIT (avec le SEO)

**Comment by lorajc** [comment]
C'est fait!
