### ISSUE TITLE
Ordre et mise en page formations et conférences

### ISSUE THREAD

**Issue by spectralshard** [betes-curieuses-design/AllianceEducation#28]
Placé par ordre de date décroissant, comme ça on retrouve les dernière conférence/formations futures (eg: 01-02-2016, 25-01-2016, ..., 19-18-01-2016.

Il faut voir ce qu'on peux faire pour avoir un mise en page correcte dans ces page.. la cliente à tous baisser la dernière fois (on applique aussi au capsule, au cas où!). Que suggère tu pour garder une mise en forme standard pour l'ensemble pour ne pas détruire la grille??

Merci!

**Comment by lorajc** [comment]
Done!
