### ISSUE TITLE
Bloc infolettre (cliente paye pour ça)

### ISSUE THREAD

**Issue by spectralshard** [betes-curieuses-design/AllianceEducation#29]
Bloc d'inscription fix dans le bas comme sur condo propriétaire (exemple) ;-)

**Comment by lorajc** [comment]
Le module de condo c'est un peut plus complexe, regard ce que j'ai fait!

**Comment by spectralshard** [comment]
C'est pas pire, pense tu qu'on peut mettre ça dans une boite qui nous suit lorsqu'on scroll? 
Avec ce que tu as mis of corse ! 

![capture d ecran 2016-01-06 a 19 57 19](https://cloud.githubusercontent.com/assets/11337449/12159406/f68b7e5e-b4af-11e5-939b-7e56241e5ce0.png)

**Comment by lorajc** [comment]
C'est fait
