### ISSUE TITLE
Changement de nom Module de l'accueil et fonction

### ISSUE THREAD

**Issue by spectralshard** [betes-curieuses-design/AllianceEducation#30]
Pour conférence et formations, ça devient  Prochaine conférence et Prochaine Formation.

Il veule avoir la possibilité de sélectionner une conférence et de la promouvoir sur l'accueil pour comblé les vides de certaine conférences/formations.

La cliente est prête à payer ici aussi! ;-)

**Comment by lorajc** [comment]
C'est fait le changement de nom
