### ISSUE TITLE
SEO

### ISSUE THREAD

**Issue by spectralshard** [betes-curieuses-design/AllianceEducation#32]
J'ai laissé tomber le module complexe qu'on c'est parler au téléphone.... une chance qu'on peu reverse les changement... ça ne fonctionnais plus dans les page ProBlog et Blog, vu qu'on modifie le layout Default... Juste corriger le OG pour les pages Pro Blog / Blog article :-)

Note: Je n'ai garder que le sitemap, déjà actif online!

Merci!

**Comment by lorajc** [comment]
Done!
