### ISSUE TITLE
Formations > Capsule Layout à ajuster

### ISSUE THREAD

**Issue by spectralshard** [betes-curieuses-design/AllianceEducation#33]
Ah on a oublier cette page a ajuster (comme conférence/formations) pour la taille des blocs dans un row.
![screen shot 2016-01-27 at 11 28 10](https://cloud.githubusercontent.com/assets/11337449/12620221/5cec4b1c-c4e9-11e5-90c7-91972dcf388d.png)

Merci ;-)

**Comment by lorajc** [comment]
Done!
