### ISSUE TITLE
Gallery Page

### ISSUE THREAD

**Issue by spectralshard** [betes-curieuses-design/AllianceEducation#34]
On va mettre le **trie par date plus récente à la date la plus ancienne**.

J'ai ajouté un buffer entre les sections photos, par contre, si on a une image bizarre ou portrait en premier, ça donne un décalage. Peut-être utiliser la fonction _CROP_ (ce que j'ai changer à l'intérieur déjà pour fixer ce problème)

![capture d écran 2016-02-02 a 20 44 40](https://cloud.githubusercontent.com/assets/11337449/12770435/5f69a290-c9ee-11e5-920a-f9c0f9abd787.png)

---

Sur tablet:

Gros problème en 768px :\

![img_0410](https://cloud.githubusercontent.com/assets/11337449/12771769/c7c78cd4-c9f9-11e5-9b80-354d24191cef.jpg)

---

Sur Mobile:

Le problème d'espacement, ici aussi, qui ne semble pas égale au autres pages du site Web.

![img_0405](https://cloud.githubusercontent.com/assets/11337449/12771785/f2383aa4-c9f9-11e5-9b57-a973bf96c403.jpg)

Merci!

**Comment by lorajc** [comment]
Le triage OK

**Comment by lorajc** [comment]
Décalage

**Comment by spectralshard** [comment]
Sound Good!
