### ISSUE TITLE
Revue de Presse

### ISSUE THREAD

**Issue by spectralshard** [betes-curieuses-design/AllianceEducation#35]
Si l'extrait est trop long, il y a un décalage d'éléments. À ajuster ici.

![capture d ecran 2016-02-02 a 21 20 33](https://cloud.githubusercontent.com/assets/11337449/12771172/0fce25e2-c9f5-11e5-8184-a85b47988381.png)

Il y a un problem dans la pagination sur cette page, j,ai tenté de regarder mais je ne comprend pas!
## ![capture d écran 2016-02-02 a 21 24 34](https://cloud.githubusercontent.com/assets/11337449/12771176/2329a4d6-c9f5-11e5-9834-ed983802d5be.png)

**Sur tablet:**
Un gros espacement entre les articles et un problem avec le menu en 768 de wide.

![img_0409](https://cloud.githubusercontent.com/assets/11337449/12771733/6e6279d8-c9f9-11e5-8496-c452515c3e3c.jpg)

---

**Sur mobile:**
Entre le titre et le début de la liste, un gros espace... un peu trop gros ;-) et aussi entre les articles.

![img_0406](https://cloud.githubusercontent.com/assets/11337449/12771752/9489a51e-c9f9-11e5-8948-1ee409b789a8.jpg)
![img_0407](https://cloud.githubusercontent.com/assets/11337449/12771753/949865fe-c9f9-11e5-8b78-2273b4f288d5.jpg)

Merci!

**Comment by lorajc** [comment]
Pagination Fixed!

**Comment by spectralshard** [comment]
Je viens de revivifier. Le reste est OK ;-) merci!
