### ISSUE TITLE
Gallery Page Inside issue

### ISSUE THREAD

**Issue by spectralshard** [betes-curieuses-design/AllianceEducation#36]
En tablet a 768px:

Il n'affiche qu'un row de photo. Peut-on le mettre a 2 ou 3?
![img_0411](https://cloud.githubusercontent.com/assets/11337449/12771802/1f68b062-c9fa-11e5-86d9-f45ef44cbc1c.jpg)

Et en mobile:
Centré la liste, pour pas que ça l'aire blizzard XD :-)

![img_0404](https://cloud.githubusercontent.com/assets/11337449/12771809/2c1abc56-c9fa-11e5-855b-6e29f4713863.jpg)

**Comment by lorajc** [comment]
Fixed!
