### ISSUE TITLE
Bloc Infolettre

### ISSUE THREAD

**Issue by spectralshard** [betes-curieuses-design/AllianceEducation#37]
J'ai mis un peu de style.

![capture d écran 2016-02-02 a 22 04 17](https://cloud.githubusercontent.com/assets/11337449/12771826/4a30151a-c9fa-11e5-81ee-40507f69924b.png)

l'idée serait que le bouton Ok soit en Mauve (secondary) et le texte de confirmation en blanc (non vert XD) Ajuster l'espace superflus en haut et en ajouter un peu en bas (égaliser)

Pour la tablet ça me va... mais pour mobile, je crois qu'on pourrait le laisser mais a 100% du browser avec mes changement ci-haut. Je vais retester par la suite :-)

**Comment by lorajc** [comment]
Fixed!
