### ISSUE TITLE
Prix français et rabais

### ISSUE THREAD

**Issue by spectralshard** [betes-curieuses-design/AllianceEducation#39]
Salut!

Ça commence à prendre bien forme! :)

Pour les prix, il va falloir que celui-ci soit de cette méthode: 20, 99 $ (le point est pour les chiffre anglais :) ), actuellement on utilise la version anglo qui est incorrecte:
![capture d ecran 2016-06-12 a 11 36 18](https://cloud.githubusercontent.com/assets/11337449/15992106/1e180528-3093-11e6-8987-7b914fd2cfbe.png)

De plus pour le rabais, il va falloir afficher le symbole % (ex: 10 %).
![capture d ecran 2016-06-12 a 11 36 32](https://cloud.githubusercontent.com/assets/11337449/15992114/382da6fc-3093-11e6-8033-9cd97c63c83f.png)
![capture d ecran 2016-06-12 a 11 36 44](https://cloud.githubusercontent.com/assets/11337449/15992115/398d02a4-3093-11e6-84d1-818f9df933fb.png)

Voilà, pour peaufiner cette partie. J'imagine que la partie ajout au panier est en cours de création, car il ne fonction pas? :)

Merci! Très beau travail mon ami!
-A

**Comment by lorajc** [comment]
Fixed!
