### ISSUE TITLE
Multi images (produits)

### ISSUE THREAD

**Issue by spectralshard** [betes-curieuses-design/AllianceEducation#40]
J'imagine que les image multiple de sont pas encore programmer (clique et changer l'image du haut)?
![capture d ecran 2016-06-12 a 11 49 59](https://cloud.githubusercontent.com/assets/11337449/15992147/c9aaaff8-3093-11e6-9f49-08acf7197497.png)

:)

**Comment by lorajc** [comment]
in process............... :)

**Comment by spectralshard** [comment]
Ahh okay sound good! :-)

**Comment by spectralshard** [comment]
Toujours pas fonctionnelle? :P

**Comment by lorajc** [comment]
Done!
