### ISSUE TITLE
Accès au panier

### ISSUE THREAD

**Issue by spectralshard** [betes-curieuses-design/AllianceEducation#41]
Je crois qu'on va devoir donner un accès dans le menu vers le panier pour effectuer un achat, car pour le moment si on quitte le panier pour faire d'autre achats et que l'on veut y retourné, on doit reclouer sur un produit. Peut-Être Séparer l'icône du panier pour y avoir accès?

![capture d ecran 2016-06-18 a 15 58 43](https://cloud.githubusercontent.com/assets/11337449/16173414/165b6042-356f-11e6-9eb0-e64b826c5f8a.png)

**Comment by lorajc** [comment]
J'ai essayé, mais il va falloir qu'on mette l'icone ailleurs.

**Comment by spectralshard** [comment]
SI on le sépare dans le menu, est-ce que ça fait un gros espace? Sinon il va falloir utiliser un sous menu pour palier à ça je crois. (Boutique: Nos articles; Mon panier)

**Comment by lorajc** [comment]
Done!
