### ISSUE TITLE
Ajout d'article dans un panier existant

### ISSUE THREAD

**Issue by spectralshard** [betes-curieuses-design/AllianceEducation#42]
Je crois que si quelqu'un à déjà le même produit et que son clique à nouveau dessus, on devrait incrémenter celui-ci ? Si on pense à quelqu'un qui veux deux fois au final un articles particulier.
![capture d ecran 2016-06-18 a 16 00 33](https://cloud.githubusercontent.com/assets/11337449/16173427/75b1160e-356f-11e6-931d-dad516795ce9.png)

**Comment by lorajc** [comment]
Cela c'est un peu difficil.

**Comment by spectralshard** [comment]
Okay. (d'où l'option question ;-) )
