### ISSUE TITLE
Panier (mobile)

### ISSUE THREAD

**Issue by spectralshard** [betes-curieuses-design/AllianceEducation#44]
Espacement pour mobile Après"Pour toute questions..."
![capture d ecran 2016-06-18 a 16 06 52](https://cloud.githubusercontent.com/assets/11337449/16173471/6db7954e-3570-11e6-84e5-5850d8f4b357.png)

Et Avant le bouton (on va faire respiré le tous! :-)
![capture d ecran 2016-06-18 a 16 06 59](https://cloud.githubusercontent.com/assets/11337449/16173484/8f81e2a6-3570-11e6-8ddc-e4e4fa64ccfa.png)

merci!

**Comment by lorajc** [comment]
Fixed
