### ISSUE TITLE
Courriel de confirmation

### ISSUE THREAD

**Issue by spectralshard** [betes-curieuses-design/AllianceEducation#46]
Il va falloir changer le sender pour info@allianceeducation.ca
![capture d ecran 2016-06-20 a 20 33 15](https://cloud.githubusercontent.com/assets/11337449/16214449/4ee20426-3726-11e6-9c5c-a26972e12ec2.png)

Same here! Elle veux utiliser l'info. Je sais que sur l'esquisse c'est son vieux courriel!!

![capture d ecran 2016-06-20 a 20 31 09](https://cloud.githubusercontent.com/assets/11337449/16214459/6b44f6a0-3726-11e6-9cde-7f35da70f2c4.png)

Article en turquoise; 20,50 $ 2,05 %; 18,45$ (Symbole et virgule (,) pour la nomenclature française)
![capture d ecran 2016-06-20 a 20 30 18](https://cloud.githubusercontent.com/assets/11337449/16214465/907f526c-3726-11e6-8031-c54f88c66af2.png)

Et finalement un peu moins d'espace entre les élément (Medias sociaux) et on va changer 2015 pour 2016 (sur le site aussi!)
![capture d ecran 2016-06-20 a 20 30 37](https://cloud.githubusercontent.com/assets/11337449/16214493/cd7918e2-3726-11e6-9220-ef927e0085d8.png)

Thumbs up!

**Comment by spectralshard** [comment]
Mettre le courriel de la cliente en CCI vu qu'elle reçois ça pour faire la facture via Pay Pall.

---

Je ne sais pas si c'est un bug ou non, mais dans les tests reçu, il semble que **le numéro de commande ne change jamais**. C'est sensé être un identifiant unique pour chaque envoi :)

**Comment by lorajc** [comment]
J'aurai le message de confirmation quand la commande est complete.

**Comment by spectralshard** [comment]
Ou transmis? Est-ce que tu as le message?

De mon côté, il manque le logo dans ton dernier test ( il est dans mon commit de la dernière fois et il manque juste les , à la place des point dans les prix/ sous total. dans le premier tableau:
![capture d ecran 2016-06-27 a 20 34 41](https://cloud.githubusercontent.com/assets/11337449/16400116/9521322e-3ca6-11e6-963b-971adddc76f9.png)

merci :-]

**Comment by lorajc** [comment]
No je n'ai pas le message

**Comment by spectralshard** [comment]
Pour le message: 

> Vous recevrez sous peu, d’ici 24h, une facture détaillée incluant les frais de livraison vers votre domicile. Merci d’avoir magasiné dans la boutique d’Alliance Éducation coaching familial!

**Comment by lorajc** [comment]
Done!
