### ISSUE TITLE
Page Boutique (mobile/tablette)

### ISSUE THREAD

**Issue by spectralshard** [betes-curieuses-design/AllianceEducation#47]
**Mobile:** Rajouter de l'espace entre les boutons et le produit suivant
![img_0033](https://cloud.githubusercontent.com/assets/11337449/16215027/47dbc8be-372c-11e6-8507-3fd1f9019548.jpg)

**Tablette:** Rajouter de l'espace entre les rows de produits
![img_0412](https://cloud.githubusercontent.com/assets/11337449/16215041/6d348998-372c-11e6-8253-31cd5ff72681.jpg)

**Comment by lorajc** [comment]
Done!
