### ISSUE TITLE
Page de produit en vente

### ISSUE THREAD

**Issue by spectralshard** [betes-curieuses-design/AllianceEducation#48]
Dans le mobile et la tablette: Ajuster le bouton LinkedIn
![img_0034](https://cloud.githubusercontent.com/assets/11337449/16215071/a92493f8-372c-11e6-8588-62501915771a.jpg)

Landscape Tablette:
![img_0413](https://cloud.githubusercontent.com/assets/11337449/16215085/c2f4b010-372c-11e6-84dc-6304e694e3ed.jpg)

Portrait Tablette:
![img_0418](https://cloud.githubusercontent.com/assets/11337449/16215087/c8d11d48-372c-11e6-8f73-b5c27cdd398d.jpg)

**Comment by spectralshard** [comment]
Est-ce que tu crois qu'on pourrais arranger la boite des images supplémentaire pour qu'elle se retrouve avant le prix? Ça fait un peu bizarre sur mobile. ;-)

Merci!

**Comment by lorajc** [comment]
Fixed
