### ISSUE TITLE
Sommaire de commandes

### ISSUE THREAD

**Issue by spectralshard** [betes-curieuses-design/AllianceEducation#49]
--BUG 1---

La fonction de **recalcule** ne fonctionne pas en version live et dev/local. Il affiche toujours le même résultat peu importe le nombre d'éléments 9999 exemple :P 

(desktop, tablette et mobile)
![capture d ecran 2016-06-20 a 21 13 56](https://cloud.githubusercontent.com/assets/11337449/16215127/2a0bcf4a-372d-11e6-96fb-ba5434a43e33.png)

--BUG/Ench 2---

Est-ce possible de mettre le champs QTS en champs nombre pour n'affiche que les chiffre sur mobile et n'accepter que les chiffre sur desktop?
![img_0035](https://cloud.githubusercontent.com/assets/11337449/16215135/39f170a4-372d-11e6-9aeb-4d0f174581d1.jpg)

**Comment by lorajc** [comment]
Fixed!
