### ISSUE TITLE
Sommaire de commandes - confirmation des données

### ISSUE THREAD

**Issue by spectralshard** [betes-curieuses-design/AllianceEducation#50]
Ahh ça j'ai briser et tu as serment vu ça dans tes courriels!

![capture d ecran 2016-06-20 a 21 14 23](https://cloud.githubusercontent.com/assets/11337449/16215165/941314f2-372d-11e6-9c48-f9a24e859d71.png)

Donc, il va falloir afficher à l'utilisateur que des champs qui sont requis ne sont pas remplis (_et ne pas envoyer temps que ceux-ci sont pas_). 

De deux, peux-t-on envoyer l'utilisateur sur une page de réussite ou les envoyer sur la page liste avec un message du system qui dit que la commande a été effectuer? Je peux te fournir le message.

Merci!

**Comment by spectralshard** [comment]
S'il n'y a pas de commande; on ne peut pas envoyer de commande (disable) et on affiche le message suivant: "Il n'y a pas d'article dans votre panier. Consulter [notre magasin](http://allianceeducation.ca/boutique) dès maintenant!"

**Comment by lorajc** [comment]
Fixed!
