### ISSUE TITLE
Boutique et page items

### ISSUE THREAD

**Issue by spectralshard** [betes-curieuses-design/AllianceEducation#51]
Salut!

J'ai fait un test avec le matériel fournis par la cliente (tu peux aller voir en live).

Tu va surement me traité de girouette, mais peut-tu enlever le contours aux images, ça va faire plus propre (you can shoot me, I know!) et mettre un lien vers la page item (Boutique) pour visualisé l'objet? :-)

Est-ce possible d'avoir le prix en secondary color comme sur l'esquisse?

**Page item:** Aussi s'il y a une seul photo est-ce possible de caché les miniatures? (ça fait bizarre!)

![capture d ecran 2016-06-22 a 21 50 34](https://cloud.githubusercontent.com/assets/11337449/16289569/1f88d9d0-38c4-11e6-8a0d-ff0fd644ce43.png)

That it, j'attends son approval pour l'image de marketing de l'accueil!
# Merci!

**Comment by lorajc** [comment]
Done!
