### ISSUE TITLE
Boutique - Partage

### ISSUE THREAD

**Issue by spectralshard** [betes-curieuses-design/AllianceEducation#52]
Ahh un petit mouton noir ce soir!

Image setter a 1200px de large:
![capture d ecran 2016-06-27 a 20 21 46](https://cloud.githubusercontent.com/assets/11337449/16399936/e02b1f84-3ca4-11e6-8839-d5f63cffd299.png)

![capture d ecran 2016-06-27 a 20 21 40](https://cloud.githubusercontent.com/assets/11337449/16399937/e211a0f2-3ca4-11e6-8d0c-7ddfffcef33f.png)

Aucun visuel dispo et le texte n'est pas pris en compte (titre et description). :\

**Comment by lorajc** [comment]
Done!
