### ISSUE TITLE
BACKEND - Liste des commandes

### ISSUE THREAD

**Issue by spectralshard** [betes-curieuses-design/AllianceEducation#53]
Salut! Sur la version live, est-ce normal que le menu des commandes soit cacher?
![capture d ecran 2016-06-28 a 21 25 09](https://cloud.githubusercontent.com/assets/11337449/16437971/6ae5444a-3d79-11e6-81bf-cbf7b44172be.png)

Merci!

**Comment by lorajc** [comment]
Done!

**Comment by spectralshard** [comment]
Question: J'ai refait la commande (vu que j'ai testé le nouveau message.. c'est normal si le numéro comm ne change pas même si j'ai mis 1 dans QTS à la place de deux ?)

**Comment by lorajc** [comment]
Supprimer la session

**Comment by lorajc** [comment]
Fixed!
