### ISSUE TITLE
Sommaire de la commande (LIVE)

### ISSUE THREAD

**Issue by spectralshard** [betes-curieuses-design/AllianceEducation#54]
Salut!

Tu ira prendre le commit que j'ai fait (2x). J'ai modifié le type du input QTÉ pour nombre 1 à 99. Ça va permettre aux browser mobile d'affiché le bon input! (Très important vu que 75 % des visite vienne du mobile) J'ai changer aussi quelques pages, mais pas de push live (voir le log des commits)

Bref, en live j'ai ce problème (même avant mes changements):
![capture d ecran 2016-06-28 a 21 22 29](https://cloud.githubusercontent.com/assets/11337449/16438020/e85a8eb2-3d79-11e6-92b3-60f62e088291.png)

J'imagine que c'est la composante qui a un problème? Si tu peux l,arranger et soumettre une copie final à la cliente par la suite! :P 

---

Aussi, si on enlève un article et qu'on tomber a 0, on devrait être rediriger à la boutique et cacher le panier (il est vide! :-) )
![capture d ecran 2016-06-28 a 21 20 54](https://cloud.githubusercontent.com/assets/11337449/16438047/298db594-3d7a-11e6-9a4f-8b8d80c10e32.png)

Voilà!

**Comment by lorajc** [comment]
Fixed!
