### ISSUE TITLE
Home page

### ISSUE THREAD

**Issue by spectralshard** [betes-curieuses-design/AllianceEducation#55]
J'ai vu que tu a mis le sidebar séparer, par contre pour la bannière celle-ci va à coté du message d'accueil de la compagnie (où il y a le bloc de vidéo), car la cliente veux qu'il soit plus haut que possible. Pas de carré gris à l'entour, c'était pour simuler la zone pour la cliente!

![capture d ecran 2016-06-28 a 20 38 44](https://cloud.githubusercontent.com/assets/11337449/16438071/722e3ca6-3d7a-11e6-9cd4-3b5f7c2025ab.png)
_Capture venant de la maquette._

Merci :-]

**Comment by lorajc** [comment]
Done!
