### ISSUE TITLE
Sommaire de la commande (LIVE) #105

### ISSUE THREAD

**Issue by spectralshard** [betes-curieuses-design/AllianceEducation#56]
Ahh Sous Mr Safari 9.1.1 et chrome, quand on supprime le dernier object, on n'est pas redirrectionner à la page de liste. :\

![capture d ecran 2016-06-29 a 21 32 45](https://cloud.githubusercontent.com/assets/11337449/16474063/5dc74df8-3e41-11e6-8689-c75d3a0e1ae1.png)

Can you fix this? :-)
Thank!

**Comment by spectralshard** [comment]
Supprimer la session + affiche le message avec un lien vers la boutique à la place du contenu. Should fix this^^

**Comment by lorajc** [comment]
Fixed!
