### ISSUE TITLE
Partage d'images (Facebook/LinkedIn - Conférences/Formations et article de blogue)

### ISSUE THREAD

**Issue by spectralshard** [betes-curieuses-design/AllianceEducation#57]
Salut!

La cliente aimerais qu'on ce règle. Lorsqu'elle créer ses articles ou conférences/formations, même si l'image est plus grande de que 1200x700px elle a toujours un problème a l'affichage soit rien pour l'image. Une fois revercher les info dans l'éditeur d'objet ça marche.. mais elle trouve ça "chiant".

J'ai fouiller un peu et je suis tombé sur ce type d'erreur... je ne sais pas si tu pourrais rendre le tout clean (sans erreur) dans le module de Facebook et réglé une bonne fois pour toute ce problème ? :-)

![capture d ecran 2016-07-03 a 11 15 55](https://cloud.githubusercontent.com/assets/11337449/16546630/cefe3254-411e-11e6-8825-fec6eabf255d.png)

![capture d ecran 2016-07-03 a 11 25 06](https://cloud.githubusercontent.com/assets/11337449/16546631/d38181fa-411e-11e6-8388-f0b2aaebbbe1.png)

Je vois qu'il y a un problème avec l'URL qui mente à :slug mais j'imagine qu'il manques d'autres boute pour s'assurer que le tous est parfait!

Et le image OG est vide :\

N'hésite pas à m'appeler s'il y a de quoi ;-)
Merci!

**Comment by lorajc** [comment]
Il faut modifier le plugin  de RainLab

**Comment by spectralshard** [comment]
Wow okay et j'imagine que ça prend un certain nombre de temps? Any other way to get this done without mod the rainlab plugin and make our customer happy?? 

---

 Je viens vérifier avec la mme et si tu peux t'arranger pour que ça fonctionne nickel, client is welling to pay for it! Hope to you! :-)

**Comment by lorajc** [comment]
Done!
