### ISSUE TITLE
Modification conférence et formation

### ISSUE THREAD

**Issue by spectralshard** [betes-curieuses-design/AllianceEducation#58]
Salut!

Petite demande de la client (et **plus d'argent pour toi!**). Elle aimerait ne pas être obliger de mettre une date (si il y a **pas de date = on n'affiche rien** dans la liste et dans la page) pour les formations/conferences.

Même chose pour **le nombre de place** (elle fait des webinaire maintenant et il n'y a pas de place max)

![capture d ecran 2016-07-03 a 11 38 47](https://cloud.githubusercontent.com/assets/11337449/16546657/91b05afc-411f-11e6-887c-d69027a336e5.png)

![capture d ecran 2016-07-03 a 12 00 18](https://cloud.githubusercontent.com/assets/11337449/16546658/97d7ff52-411f-11e6-88b7-232bfaf060f6.png)

Pour l'instant elle a mis une date bidon, mais si on met rien, ça affiche la date du jour. :P 

(Tu pourra rajouter ça **en extra dans la facture final** (pour le _séparer du montant de la boutique_) :-)

Merci!

**Comment by lorajc** [comment]
Done!

**Comment by spectralshard** [comment]
Ahh tu as oublier la page intérieur, quand tu aura quelques minute hehe!

![capture d ecran 2016-07-16 a 16 25 33](https://cloud.githubusercontent.com/assets/11337449/16896990/ff39f69e-4b71-11e6-9ff9-ad9804b3ed13.png)

**Comment by lorajc** [comment]
Done!
