### ISSUE TITLE
Backend Issue

### ISSUE THREAD

**Issue by spectralshard** [betes-curieuses-design/AllianceEducation#59]
Salut! deux plugin semble avoir des problèmes:
![capture d ecran 2016-10-15 a 15 03 02](https://cloud.githubusercontent.com/assets/11337449/19412665/c66ed9d8-92e8-11e6-83cb-5552459dc4bc.png)

et 

![capture d ecran 2016-10-15 a 15 03 08](https://cloud.githubusercontent.com/assets/11337449/19412668/ca7b5e98-92e8-11e6-8585-a1447cb8b71d.png)

Merci!

**Comment by lorajc** [comment]
Fixed!

**Comment by spectralshard** [comment]
Nop encore le même problème avec la galerie photo :/

**Comment by lorajc** [comment]
Fixed!
