### ISSUE TITLE
Formation and conférence page : Typo error

### ISSUE THREAD

**Issue by spectralshard** [betes-curieuses-design/AllianceEducation#7]
Just a capital for: M'inscrire
![capture d ecran 2015-11-25 a 21 14 12](https://cloud.githubusercontent.com/assets/11337449/11413694/008854ac-93ba-11e5-9b47-163e324e1a3b.png)

J majuscule ;-)
![2082ad5e-953e-11e5-9237-06c9e4f79d04](https://cloud.githubusercontent.com/assets/11337449/11449584/4acb8e90-9549-11e5-8892-6fc1644699e9.png)

**Comment by spectralshard** [comment]
Don't forget the ability to have 1 feature image (as we speak today:) ) for both of those section also ^^

**Comment by spectralshard** [comment]
J majuscule ;-) Merci!
![capture d ecran 2015-11-27 a 19 35 52](https://cloud.githubusercontent.com/assets/11337449/11449311/2082ad5e-953e-11e5-9237-06c9e4f79d04.png)

**Comment by lorajc** [comment]
Fixed!
