### ISSUE TITLE
Home page - Space issue

### ISSUE THREAD

**Issue by spectralshard** [betes-curieuses-design/AllianceEducation#9]
A little bit of space between blog micro post :-)
Can you remove the rounded effect on the top of the Blogue head also?
![capture d ecran 2015-11-25 a 21 12 52](https://cloud.githubusercontent.com/assets/11337449/11413713/5a1f961a-93ba-11e5-92f4-0a45f2515582.png)

**Comment by lorajc** [comment]
Fixed!
